### ISSUE TITLE
[wantfix] 環境変数のデフォルト値指定について

### ISSUE THREAD

**Issue by rk76feWF** [Shakkuuu/kiso-lab-support-tool#1]
Dockerで使用する際、環境変数のデフォルト値を指定しないと起動に失敗します。
特に、ポートに関しては、二重に指定する必要があって煩雑ではないでしょうか？

```yaml
services:
  pdf-share-tool:
    image: shakku/kiso-lab-support-tool
    container_name: pdf-share-tool
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - USER_ENV="tmcit"
      - PASSWORD_ENV="tmcit"
      - PORT_ENV=8080
```

Dockerfileでデフォルト値を指定することを提案します。
